apiVersion: batch/v1
kind: Job
metadata:
  generateName: cdso-hook-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: echo
          image: alpine:3.7
          command: ["echo", "Hello, World!"]