---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: orchestration
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/argoproj/argo-cd
      path: manifests/cluster-install
      targetRevision: stable
      kustomize:
        patches:
          # Rollouts UI extension patch to argocd-server
          - target:
              kind: Deployment
              name: argocd-server
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: argocd-server
              spec:
                template:
                  spec:
                    initContainers:
                      - name: extension-rollouts
                        image: quay.io/argoprojlabs/argocd-extension-installer:latest
                        env:
                          - name: EXTENSION_URL
                            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.6/extension.tar
                        volumeMounts:
                          - name: extensions
                            mountPath: /tmp/extensions
                        securityContext:
                          runAsUser: 1000
                          allowPrivilegeEscalation: false
                    containers:
                      - name: argocd-server
                        volumeMounts:
                          - name: extensions
                            mountPath: /tmp/extensions
                    volumes:
                      - name: extensions
                        emptyDir: {}
                    
    - repoURL: https://github.com/beckadd/cdso-services
      path: admin/config
      targetRevision: HEAD
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
