---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: orchestration
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    path: manifests/cluster-install
    targetRevision: stable
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
