---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: orchestration
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/prometheus-operator/kube-prometheus
    path: manifests
    targetRevision: v0.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
