---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: orchestration
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/prometheus-operator/kube-prometheus
      path: manifests
      targetRevision: v0.*
      directory:
        recurse: true
    - repoURL: https://github.com/beckadd/cdso-services
      path: admin/monitoring
      targetRevision: HEAD
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "ServerSideApply=true"