---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: admin
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "!infrastructure"
    - "*"
  destinations:
    # the admin project is only allowed to manage apps in this cluster.
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
