---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-rollout
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/beckadd/cdso-services
    path: example-rollout/manifests
    targetRevision: HEAD # typically you'd want a tagged version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true