---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: infrastructure
spec:
  project: infrastructure
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
