apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  sourceRepos:
    - "*"
  sourceNamespaces:
    - infrastructure
  destinations:
    # the infrastructure project is only allowed to manage apps in this namespace.
    - namespace: infrastructure
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"